import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import 'bootstrap/dist/css/bootstrap.min.css';
import AuthClient from "@/services/client/common/ClientServices/authserviceClient";
import HeaderComponent from "@/components/ClassComponents/HeaderComponent/HeaderComponent";
import Menu from "@/components/ClassComponents/Menu/Menu";
/*
npm install @mui/material @emotion/react @emotion/styled --legacy-peer-deps

*/
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased header-content-footer-container`}
      >
        <div className="header-content-footer-container">
            <header className="hcf-header">
              <HeaderComponent></HeaderComponent>
            </header>

            <div className="hcf-content">
              <nav className="left-side-menu">
                <Menu />
              </nav>

              <main className="right-side-content">
                {children}
              </main>
            </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
